Repository milvus-io/milvus-storage, pull requests merged in 2023-11, with the labels that each got.

#85 [Go] Fix manifest test
  go/storage/manifest/manifest_test.go
Labels: lgtm, approved, size/XS

#83 Fix fs path mismatch in go and cpp
  .gitignore
  cpp/src/common/arrow_util.cpp
  go/io/fs/minio_fs.go
  go/io/fs/minio_fs_test.go
Labels: lgtm, approved, size/L

#86 [Cpp] Create blob directory in Open
  cpp/include/milvus-storage/common/utils.h
  cpp/src/common/utils.cpp
  cpp/src/storage/space.cpp
Labels: lgtm, approved, size/XS

#87 Add get curr version
  cpp/include/milvus-storage/storage/space.h
  cpp/src/storage/space.cpp
Labels: lgtm, approved, size/XS

#88 [Cpp] Update manfiest version after write blobs
  cpp/src/storage/space.cpp
Labels: lgtm, approved, size/XS

#89 [Cpp] Remove logs
  cpp/src/common/arrow_util.cpp
Labels: lgtm, approved, size/XS

#90 [Go] Add StatisticsBlobs
  go/storage/manifest/manifest.go
  go/storage/space.go
Labels: lgtm, approved, size/XS

#91 Add opendal fs implement
  cpp/CMakeLists.txt
  cpp/cmake/libopendal.cmake
  cpp/conanfile.py
  cpp/include/milvus-storage/common/opendal_fs.h
  cpp/src/common/fs_util.cpp
  cpp/src/common/opendal_fs.cpp
Labels: lgtm, approved, size/L

#92 [Go]: Fix return wrong error
  go/storage/schema/schema.go
Labels: lgtm, approved, size/XS

#95 [Cpp]: Fix mem leak
  cpp/src/storage/space.cpp
Labels: lgtm, approved, size/S
