Repository milvus-io/milvus-storage, pull requests merged in 2023-07, with the labels that each got.

#20 Fix skip cpp ut error
  .github/workflows/cpp-ci.yml
  cpp/CMakeLists.txt
  cpp/test/CMakeLists.txt
Labels: bug, cpp

#22 feat(schema): add unit tests for schema by cpp.
  cpp/Makefile
  cpp/test/schema_test.cpp
Labels: lgtm, approved, size/L

#24 feat(space): refactor and improve Storage Space functionality
  cpp/src/common/fs_util.cpp
  cpp/src/common/fs_util.h
  cpp/src/common/utils.cpp
  cpp/src/common/utils.h
  cpp/src/storage/schema.cpp
  cpp/src/storage/space.cpp
  cpp/src/storage/space.h
  cpp/test/schema_test.cpp
  cpp/test/space_test.cpp
Labels: lgtm, approved, size/L

#25 Change manfiest file dir to versions
  cpp/src/common/constants.h
  cpp/src/common/utils.cpp
  cpp/src/common/utils.h
  cpp/src/storage/space.cpp
  cpp/src/storage/space.h
Labels: lgtm, approved, size/M

#27 Add Space::Open
  cpp/src/common/constants.h
  cpp/src/common/status.h
  cpp/src/common/utils.cpp
  cpp/src/common/utils.h
  cpp/src/storage/manifest.cpp
  cpp/src/storage/manifest.h
  cpp/src/storage/options.cpp
  cpp/src/storage/options.h
  cpp/src/storage/space.cpp
  cpp/src/storage/space.h
  cpp/test/manifest_test.cpp
  cpp/test/options_test.cpp
  cpp/test/schema_test.cpp
  cpp/test/space_test.cpp
Labels: lgtm, approved, size/L

#26 feat(log): add glog library and logging capabilities.
  cpp/CMakeLists.txt
  cpp/conanfile.py
  cpp/src/common/log.cpp
  cpp/src/common/log.h
  cpp/src/storage/schema.cpp
  cpp/test/CMakeLists.txt
Labels: lgtm, approved, size/L

#29 feat(log):add zap library and logging capabilities
  go/common/constant.go
  go/common/log/field.go
  go/common/log/log.go
  go/common/log/log_test.go
  go/common/log/options.go
  go/common/utils/utils.go
  go/go.mod
  go/go.sum
  go/io/fs/local_fs.go
  go/storage/default_space.go
  go/storage/manifest/manifest.go
  go/storage/manifest/manifest_test.go
  go/storage/schema/schema.go
  go/storage/schema/schema_test.go
  go/storage/space_test.go
Labels: lgtm, approved, size/L

#28 Fix writer count error
  cpp/src/format/parquet/file_writer.cpp
Labels: lgtm, approved, size/XS

#30 Fix manfiest version allocation error
  cpp/src/storage/space.cpp
  cpp/src/storage/space.h
  cpp/test/space_test.cpp
Labels: lgtm, approved, size/M

#31 Add some test utils macro
  cpp/src/common/utils.cpp
  cpp/src/storage/test_util.h
  cpp/test/CMakeLists.txt
  cpp/test/options_test.cpp
  cpp/test/schema_test.cpp
  cpp/test/space_test.cpp
  cpp/test/test_util.cpp
  cpp/test/test_util.h
Labels: lgtm, approved, size/L

#33 Fix some read bugs and add a simple read test
  cpp/src/file/delete_fragment.cpp
  cpp/src/file/delete_fragment.h
  cpp/src/filter/filter.h
  cpp/src/filter/value.cpp
  cpp/src/filter/value.h
  cpp/src/reader/common/delete_reader.cpp
  cpp/src/reader/common/delete_reader.h
  cpp/src/reader/common/filter_reader.cpp
  cpp/src/reader/filter_query_record_reader.cpp
  cpp/src/reader/merge_record_reader.cpp
  cpp/src/reader/multi_files_sequential_reader.cpp
  cpp/src/reader/multi_files_sequential_reader.h
  cpp/src/reader/scan_record_reader.cpp
  cpp/src/storage/options.h
  cpp/src/storage/space.cpp
  cpp/src/storage/space.h
  cpp/test/space_test.cpp
  cpp/test/test_util.h
Labels: lgtm, approved, size/L

#34 Fix open error
  cpp/src/storage/manifest.h
  cpp/src/storage/options.h
  cpp/src/storage/space.cpp
  cpp/test/space_test.cpp
Labels: lgtm, approved, size/S
