Repository milvus-io/milvus-storage, pull requests merged in 2023-10, with the labels that each got.

#69 [Go & Cpp] Validate schema when opening a space
  cpp/src/storage/space.cpp
  go/storage/space.go
Labels: lgtm, approved, size/XS

#70 [Go & Cpp] Fix vector type check
  cpp/src/storage/options.cpp
  cpp/test/options_test.cpp
  go/storage/schema/schema_option.go
Labels: lgtm, approved, size/S

#71 [Go] List objects recursively
  go/io/fs/minio_fs.go
  go/io/fs/minio_fs_test.go
Labels: lgtm, approved, size/S

#72 [Go] Redesign uri format to make it same with arrow
  go/common/constant/constant.go
  go/common/errors/errors.go
  go/io/fs/minio_fs.go
  go/io/fs/minio_fs_test.go
  go/storage/manifest/manifest.go
  go/storage/transaction/transaction.go
Labels: lgtm, approved, size/L

#73 [Go] Fix fixed size list type serialization
  go/common/utils/utils.go
Labels: lgtm, approved, size/XS

#74 [Cpp] Enable s3 fs
  cpp/CMakeLists.txt
  cpp/conanfile.py
  cpp/src/common/fs_util.cpp
Labels: lgtm, approved, size/S

#75 [Cpp] Initialize s3
  cpp/src/common/fs_util.cpp
Labels: lgtm, approved, size/XS

#76 [Cpp] Finalize s3 before the end
  cpp/include/milvus-storage/storage/space.h
  cpp/src/common/fs_util.cpp
  cpp/src/storage/space.cpp
Labels: lgtm, approved, size/S

#77 [Cpp] Call FinalizeS3 at exit
  cpp/include/milvus-storage/storage/space.h
  cpp/src/common/fs_util.cpp
  cpp/src/storage/space.cpp
Labels: lgtm, approved, size/S

#78 [Cpp] Pass path as output argument when BuildFileSystem
  cpp/include/milvus-storage/common/fs_util.h
  cpp/src/common/fs_util.cpp
  cpp/src/storage/space.cpp
  cpp/test/multi_files_sequential_reader_test.cpp
Labels: lgtm, approved, size/S

#79 [Cpp] Add Schema function
  .gitignore
  cpp/include/milvus-storage/storage/space.h
  cpp/src/storage/space.cpp
Labels: lgtm, approved, size/XS

#80 [Cpp] Remove compiler warning about macro redefined
  cpp/include/milvus-storage/common/macro.h
Labels: lgtm, approved, size/XS

#81 [Cpp] Schema return storage's schema
  cpp/include/milvus-storage/storage/space.h
  cpp/src/storage/space.cpp
Labels: lgtm, approved, size/XS

#82 [Go] Fix fragment may not be recorded in manifest issue
  go/storage/transaction/transaction.go
Labels: lgtm, approved, size/XS

#68 [Go] support concurrent writing, fix concurrent bug, add some unit test
  go/io/fs/fs.go
  go/io/fs/local_fs.go
  go/io/fs/memory_fs.go
  go/io/fs/minio_fs.go
  go/storage/lock/lock_manager.go
  go/storage/manifest/commit.go
  go/storage/manifest/manifest.go
  go/storage/manifest/manifest_test.go
  go/storage/manifest/reader_writer.go
  go/storage/space_test.go
  go/storage/transaction/transaction_test.go
Labels: lgtm, approved, size/XL
