Repository milvus-io/milvus-storage, pull requests merged in 2024-08, with the labels that each got.

#124 column group splitter
  cpp/include/milvus-storage/writer/splitter/size_based_splitter.h
  cpp/include/milvus-storage/writer/splitter/splitter_plugin.h
  cpp/src/writer/splitter/size_based_splitter.cpp
  cpp/test/writer/splitter/size_based_splitter_test.cpp
Labels: lgtm, approved, size/L

#129 feat: adding packed reader
  cpp/include/milvus-storage/common/arrow_util.h
  cpp/include/milvus-storage/packed/reader.h
  cpp/src/common/arrow_util.cpp
  cpp/src/packed/reader.cpp
  cpp/test/packed/reader_test.cpp
Labels: lgtm, approved, size/L

#130 clean up reader and writer
  cpp/include/milvus-storage/packed/reader.h
  cpp/src/packed/reader.cpp
  cpp/test/packed/reader_test.cpp
  cpp/test/writer/splitter/indices_based_splitter_test.cpp
  cpp/test/writer/splitter/size_based_splitter_test.cpp
  cpp/test/writer/splitter/splitter_test_base.h
Labels: lgtm, approved, size/L

#133 enhance: fix packed reader and writer
  OWNERS
  cpp/conanfile.py
  cpp/include/milvus-storage/format/parquet/file_writer.h
  cpp/include/milvus-storage/packed/column_group.h
  cpp/include/milvus-storage/packed/column_group_writer.h
  cpp/include/milvus-storage/packed/reader.h
  cpp/include/milvus-storage/packed/writer.h
  cpp/src/common/fs_util.cpp
  cpp/src/format/parquet/file_writer.cpp
  cpp/src/packed/column_group.cpp
  cpp/src/packed/column_group_writer.cpp
  cpp/src/packed/reader.cpp
  cpp/src/packed/splitter/size_based_splitter.cpp
  cpp/src/packed/writer.cpp
  cpp/test/packed/column_group_test.cpp
  cpp/test/packed/packed_integration_test.cpp
  cpp/test/packed/reader_test.cpp
Labels: lgtm, approved, size/L

#135 [feat] add dev docker container
  README.md
  cpp/Dockerfile
  cpp/requirements.txt
Labels: lgtm, approved, size/M

#136 enhance: support multiple reading row groups to avoid missing data
  cpp/include/milvus-storage/packed/chunk_manager.h
  cpp/include/milvus-storage/packed/reader.h
  cpp/include/milvus-storage/packed/writer.h
  cpp/src/packed/chunk_manager.cpp
  cpp/src/packed/reader.cpp
  cpp/src/packed/writer.cpp
  cpp/test/packed/chunk_manager_test.cpp
  cpp/test/packed/packed_integration_test.cpp
Labels: lgtm, approved, size/L

#137 enhance: fix ut for large batches
  cpp/include/milvus-storage/packed/column_group_writer.h
  cpp/src/packed/column_group_writer.cpp
  cpp/src/packed/reader.cpp
  cpp/test/packed/packed_integration_test.cpp
Labels: lgtm, approved, size/M

#138 add s3 fs validation
  .github/workflows/cpp-ci.yml
  cpp/CMakeLists.txt
  cpp/conanfile.py
  cpp/include/milvus-storage/common/fs_util.h
  cpp/include/milvus-storage/storage/space.h
  cpp/src/common/fs_util.cpp
  cpp/src/storage/space.cpp
  cpp/test/packed/packed_integration_test.cpp
  cpp/test/packed/reader_test.cpp
Labels: lgtm, approved, size/M

#139 fix packed writer memory limit
  cpp/include/milvus-storage/common/fs_util.h
  cpp/include/milvus-storage/format/parquet/file_writer.h
  cpp/src/format/parquet/file_writer.cpp
  cpp/src/packed/writer.cpp
  cpp/test/packed/packed_integration_test.cpp
Labels: lgtm, approved, size/S
