Repository milvus-io/milvus-storage, pull requests merged in 2025-05, with the labels that each got.

#191 fix: s3fs client finalizer should be a singleton
  cpp/src/filesystem/s3/multi_part_upload_s3_fs.cpp
Labels: lgtm, approved, size/XS

#190 enhance: Set S3Options address as-is
  cpp/include/milvus-storage/filesystem/s3/s3_fs.h
  cpp/src/filesystem/s3/multi_part_upload_s3_fs.cpp
  cpp/src/filesystem/s3/s3_fs.cpp
  cpp/test/filesystem/s3_fs_test.cpp
Labels: lgtm, approved, size/S

#192 enhance: Throw error when packed rw init fail
  cpp/src/packed/reader.cpp
  cpp/src/packed/writer.cpp
Labels: lgtm, approved, size/S

#194 agpl v3 and sspl v1 licensing
  LICENSE
  licenses/LICENSE.AGPL.3.0.txt
  licenses/LICENSE.SSPL.1.0.txt
Labels: lgtm, approved, size/XS

#196 fix: workaround compatibility issue between AWS SDK and MinIO [GH-45304]
  cpp/src/filesystem/s3/multi_part_upload_s3_fs.cpp
Labels: lgtm, approved, size/S

#199 fix: Use PutObject request for S3 in OutputStream when only uploading…
  cpp/src/filesystem/s3/multi_part_upload_s3_fs.cpp
Labels: lgtm, approved, size/L
