Repository milvus-io/milvus-storage, pull requests merged in 2025-08, with the labels that each got.

#230 enhance: Use filesystem to create parent dir
  cpp/src/format/parquet/file_writer.cpp
Labels: lgtm, approved, size/S

#231 enhance: support default zstd compression for writer
  cpp/src/packed/column_group_writer.cpp
  cpp/test/packed/packed_integration_test.cpp
Labels: lgtm, approved, size/M

#233 enhance: adding filesystem io metrics
  cpp/CMakeLists.txt
  cpp/include/milvus-storage/filesystem/s3/multi_part_upload_s3_fs.h
  cpp/src/filesystem/s3/multi_part_upload_s3_fs.cpp
  cpp/src/packed/splitter/indices_based_splitter.cpp
  cpp/src/packed/writer.cpp
  cpp/test/CMakeLists.txt
  cpp/test/include/test_util.h
  cpp/test/s3_client_metrics_test.cpp
Labels: lgtm, approved, size/L

#235 fix: Use `GetContentLength()` preventing seek to end
  cpp/src/filesystem/s3/multi_part_upload_s3_fs.cpp
Labels: lgtm, approved, size/XS

#234 enhance: adding new API set
  cpp/CMakeLists.txt
  cpp/include/milvus-storage/manifest.h
  cpp/include/milvus-storage/reader.h
  cpp/include/milvus-storage/writer.h
  cpp/src/manifest.cpp
  cpp/src/reader.cpp
  cpp/src/writer.cpp
Labels: lgtm, approved, size/XXL
