Repository milvus-io/milvus-storage, pull requests merged in 2025-09, with the labels that each got.

#244 enhance: Set ExtendedS3Option bucket name
  cpp/src/filesystem/s3/s3_fs.cpp
Labels: lgtm, approved, size/XS

#240 enhance: throw exception from io close destructor
  cpp/include/milvus-storage/filesystem/io/io_util.h
Labels: lgtm, approved, size/XS

#250 fix: azure fs should not part upload
  cpp/include/milvus-storage/common/constants.h
  cpp/include/milvus-storage/filesystem/s3/multi_part_upload_s3_fs.h
  cpp/src/format/parquet/file_writer.cpp
  cpp/src/packed/writer.cpp
Labels: lgtm, approved, size/S

#251 enhance: Revert bucket name push down PRs
  cpp/include/milvus-storage/filesystem/s3/multi_part_upload_s3_fs.h
  cpp/src/filesystem/s3/multi_part_upload_s3_fs.cpp
  cpp/src/filesystem/s3/s3_fs.cpp
  cpp/test/s3_client_metrics_test.cpp
Labels: lgtm, approved, size/M

#252 enhance: Expose API to create non-singleton fs
  cpp/include/milvus-storage/filesystem/fs.h
  cpp/src/filesystem/fs.cpp
Labels: lgtm, approved, size/XS

#255 fix: force virtual host for oss and cos
  cpp/src/filesystem/s3/s3_fs.cpp
Labels: lgtm, approved, size/XS

#265 fix: invalid check-format and fix-format in Makefile
  cpp/Makefile
Labels: lgtm, approved, size/S

#254 enhance: Introduce vortex writer into storage
  cpp/CMakeLists.txt
  cpp/include/milvus-storage/format/vortex/vortex_writer.h
  cpp/src/format/parquet/file_writer.cpp
  cpp/src/format/vortex/vortex_writer.cpp
  cpp/src/format/vortex/vx-bridge/.gitignore
  cpp/src/format/vortex/vx-bridge/Cargo.lock
  cpp/src/format/vortex/vx-bridge/Cargo.toml
  cpp/src/format/vortex/vx-bridge/src/errcode.rs
  cpp/src/format/vortex/vx-bridge/src/include/error_ffi.h
  cpp/src/format/vortex/vx-bridge/src/include/object_store_ffi.h
  cpp/src/format/vortex/vx-bridge/src/include/object_store_writer_ffi.h
  cpp/src/format/vortex/vx-bridge/src/include/test_ffi.h
  cpp/src/format/vortex/vx-bridge/src/lib.rs
  cpp/src/format/vortex/vx-bridge/src/objstore.rs
  cpp/src/format/vortex/vx-bridge/src/objwriter.rs
  cpp/src/format/vortex/vx-bridge/src/test.rs
  cpp/src/format/vortex/vx-bridge/tests/test-c-ffi.c
  cpp/test/format/vortex/file_writer_test.cpp
Labels: lgtm, approved, size/XXL
